# Form implementation generated from reading ui file 'UI_LoadTransferFunctionPopUp.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadTransferFunctionPopUp(object):
    def setupUi(self, LoadTransferFunctionPopUp):
        LoadTransferFunctionPopUp.setObjectName("LoadTransferFunctionPopUp")
        LoadTransferFunctionPopUp.resize(400, 415)
        self.gridLayout = QtWidgets.QGridLayout(LoadTransferFunctionPopUp)
        self.gridLayout.setObjectName("gridLayout")
        self.TransferFunctionLineEdit = QtWidgets.QLineEdit(LoadTransferFunctionPopUp)
        self.TransferFunctionLineEdit.setObjectName("TransferFunctionLineEdit")
        self.gridLayout.addWidget(self.TransferFunctionLineEdit, 0, 0, 1, 2)
        self.LineTypeLabel = QtWidgets.QLabel(LoadTransferFunctionPopUp)
        self.LineTypeLabel.setObjectName("LineTypeLabel")
        self.gridLayout.addWidget(self.LineTypeLabel, 2, 0, 1, 1)
        self.LineTypeCB = QtWidgets.QComboBox(LoadTransferFunctionPopUp)
        self.LineTypeCB.setObjectName("LineTypeCB")
        self.gridLayout.addWidget(self.LineTypeCB, 2, 1, 1, 1)
        self.ColorLabel = QtWidgets.QLabel(LoadTransferFunctionPopUp)
        self.ColorLabel.setObjectName("ColorLabel")
        self.gridLayout.addWidget(self.ColorLabel, 3, 0, 1, 1)
        self.ColorButton = QtWidgets.QPushButton(LoadTransferFunctionPopUp)
        self.ColorButton.setMinimumSize(QtCore.QSize(30, 30))
        self.ColorButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ColorButton.setText("")
        self.ColorButton.setObjectName("ColorButton")
        self.gridLayout.addWidget(self.ColorButton, 3, 1, 1, 1)
        self.TraceNameLabel = QtWidgets.QLabel(LoadTransferFunctionPopUp)
        self.TraceNameLabel.setObjectName("TraceNameLabel")
        self.gridLayout.addWidget(self.TraceNameLabel, 4, 0, 1, 1)
        self.TraceNameLE = QtWidgets.QLineEdit(LoadTransferFunctionPopUp)
        self.TraceNameLE.setObjectName("TraceNameLE")
        self.gridLayout.addWidget(self.TraceNameLE, 4, 1, 1, 1)
        self.CheckButton = QtWidgets.QPushButton(LoadTransferFunctionPopUp)
        self.CheckButton.setObjectName("CheckButton")
        self.gridLayout.addWidget(self.CheckButton, 5, 0, 1, 1)
        self.TransferFunctionButtonBox = QtWidgets.QDialogButtonBox(LoadTransferFunctionPopUp)
        self.TransferFunctionButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.TransferFunctionButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.TransferFunctionButtonBox.setObjectName("TransferFunctionButtonBox")
        self.gridLayout.addWidget(self.TransferFunctionButtonBox, 5, 1, 1, 1)
        self.TexGroupBox = QtWidgets.QGroupBox(LoadTransferFunctionPopUp)
        self.TexGroupBox.setMinimumSize(QtCore.QSize(0, 175))
        self.TexGroupBox.setObjectName("TexGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TexGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.TexGroupBox, 1, 0, 1, 2)

        self.retranslateUi(LoadTransferFunctionPopUp)
        self.TransferFunctionButtonBox.rejected.connect(LoadTransferFunctionPopUp.reject) # type: ignore
        self.TransferFunctionButtonBox.accepted.connect(LoadTransferFunctionPopUp.accept) # type: ignore
        self.CheckButton.clicked.connect(LoadTransferFunctionPopUp.updateTransferFunction) # type: ignore
        self.TransferFunctionLineEdit.textEdited['QString'].connect(LoadTransferFunctionPopUp.textChange) # type: ignore
        self.ColorButton.clicked.connect(LoadTransferFunctionPopUp.ChooseColor) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoadTransferFunctionPopUp)

    def retranslateUi(self, LoadTransferFunctionPopUp):
        _translate = QtCore.QCoreApplication.translate
        LoadTransferFunctionPopUp.setWindowTitle(_translate("LoadTransferFunctionPopUp", "Dialog"))
        self.LineTypeLabel.setText(_translate("LoadTransferFunctionPopUp", "Tipo de linea"))
        self.ColorLabel.setText(_translate("LoadTransferFunctionPopUp", "Color"))
        self.TraceNameLabel.setText(_translate("LoadTransferFunctionPopUp", "Nombre de linea"))
        self.CheckButton.setText(_translate("LoadTransferFunctionPopUp", "Check"))
        self.TexGroupBox.setTitle(_translate("LoadTransferFunctionPopUp", "Interpretado como"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadTransferFunctionPopUp = QtWidgets.QDialog()
    ui = Ui_LoadTransferFunctionPopUp()
    ui.setupUi(LoadTransferFunctionPopUp)
    LoadTransferFunctionPopUp.show()
    sys.exit(app.exec())
