# Form implementation generated from reading ui file 'UI_LoadTransferFunctionPopUp.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoadTransferFunctionPopUp(object):
    def setupUi(self, LoadTransferFunctionPopUp):
        LoadTransferFunctionPopUp.setObjectName("LoadTransferFunctionPopUp")
        LoadTransferFunctionPopUp.resize(400, 384)
        self.gridLayout = QtWidgets.QGridLayout(LoadTransferFunctionPopUp)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TransferFunctionTextBox = QtWidgets.QTextEdit(LoadTransferFunctionPopUp)
        self.TransferFunctionTextBox.setObjectName("TransferFunctionTextBox")
        self.verticalLayout.addWidget(self.TransferFunctionTextBox)
        self.groupBox = QtWidgets.QGroupBox(LoadTransferFunctionPopUp)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 175))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout.addWidget(self.groupBox)
        self.TransferFunctionButtonBox = QtWidgets.QDialogButtonBox(LoadTransferFunctionPopUp)
        self.TransferFunctionButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.TransferFunctionButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.TransferFunctionButtonBox.setObjectName("TransferFunctionButtonBox")
        self.verticalLayout.addWidget(self.TransferFunctionButtonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(LoadTransferFunctionPopUp)
        self.TransferFunctionButtonBox.rejected.connect(LoadTransferFunctionPopUp.reject) # type: ignore
        self.TransferFunctionButtonBox.accepted.connect(LoadTransferFunctionPopUp.accept) # type: ignore
        self.TransferFunctionTextBox.textChanged.connect(LoadTransferFunctionPopUp.updateTransferFunction) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoadTransferFunctionPopUp)

    def retranslateUi(self, LoadTransferFunctionPopUp):
        _translate = QtCore.QCoreApplication.translate
        LoadTransferFunctionPopUp.setWindowTitle(_translate("LoadTransferFunctionPopUp", "Dialog"))
        self.groupBox.setTitle(_translate("LoadTransferFunctionPopUp", "Interpretado como"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoadTransferFunctionPopUp = QtWidgets.QDialog()
    ui = Ui_LoadTransferFunctionPopUp()
    ui.setupUi(LoadTransferFunctionPopUp)
    LoadTransferFunctionPopUp.show()
    sys.exit(app.exec())
