# Form implementation generated from reading ui file 'UI_ModTracePopUp.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModTracePopUp(object):
    def setupUi(self, ModTracePopUp):
        ModTracePopUp.setObjectName("ModTracePopUp")
        ModTracePopUp.resize(393, 307)
        self.gridLayout = QtWidgets.QGridLayout(ModTracePopUp)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(ModTracePopUp)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ColorButton = QtWidgets.QPushButton(ModTracePopUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorButton.sizePolicy().hasHeightForWidth())
        self.ColorButton.setSizePolicy(sizePolicy)
        self.ColorButton.setMinimumSize(QtCore.QSize(30, 30))
        self.ColorButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ColorButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ColorButton.setText("")
        self.ColorButton.setObjectName("ColorButton")
        self.horizontalLayout.addWidget(self.ColorButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(ModTracePopUp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.TraceTypeCB = QtWidgets.QComboBox(ModTracePopUp)
        self.TraceTypeCB.setObjectName("TraceTypeCB")
        self.gridLayout.addWidget(self.TraceTypeCB, 1, 2, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ModTracePopUp)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.label = QtWidgets.QLabel(ModTracePopUp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.TraceNameLE = QtWidgets.QLineEdit(ModTracePopUp)
        self.TraceNameLE.setObjectName("TraceNameLE")
        self.gridLayout.addWidget(self.TraceNameLE, 3, 2, 1, 1)
        self.MarkerLabel = QtWidgets.QLabel(ModTracePopUp)
        self.MarkerLabel.setObjectName("MarkerLabel")
        self.gridLayout.addWidget(self.MarkerLabel, 2, 0, 1, 1)
        self.MarkersCB = QtWidgets.QComboBox(ModTracePopUp)
        self.MarkersCB.setObjectName("MarkersCB")
        self.gridLayout.addWidget(self.MarkersCB, 2, 2, 1, 1)

        self.retranslateUi(ModTracePopUp)
        self.buttonBox.accepted.connect(ModTracePopUp.accept) # type: ignore
        self.buttonBox.rejected.connect(ModTracePopUp.reject) # type: ignore
        self.ColorButton.clicked.connect(ModTracePopUp.ChooseColor) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModTracePopUp)

    def retranslateUi(self, ModTracePopUp):
        _translate = QtCore.QCoreApplication.translate
        ModTracePopUp.setWindowTitle(_translate("ModTracePopUp", "Dialog"))
        self.label_3.setText(_translate("ModTracePopUp", "Color de curva"))
        self.label_2.setText(_translate("ModTracePopUp", "Tipo de Curva"))
        self.label.setText(_translate("ModTracePopUp", "Nombre de la curva"))
        self.MarkerLabel.setText(_translate("ModTracePopUp", "Marcadores"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModTracePopUp = QtWidgets.QDialog()
    ui = Ui_ModTracePopUp()
    ui.setupUi(ModTracePopUp)
    ModTracePopUp.show()
    sys.exit(app.exec())
