# Form implementation generated from reading ui file 'UI_ModTFTracePopUp.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModTFTracePopUp(object):
    def setupUi(self, ModTFTracePopUp):
        ModTFTracePopUp.setObjectName("ModTFTracePopUp")
        ModTFTracePopUp.resize(406, 501)
        self.gridLayout = QtWidgets.QGridLayout(ModTFTracePopUp)
        self.gridLayout.setObjectName("gridLayout")
        self.TFLabel = QtWidgets.QLabel(ModTFTracePopUp)
        self.TFLabel.setObjectName("TFLabel")
        self.gridLayout.addWidget(self.TFLabel, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(ModTFTracePopUp)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 0, 1, 1)
        self.TFLineEdit = QtWidgets.QLineEdit(ModTFTracePopUp)
        self.TFLineEdit.setObjectName("TFLineEdit")
        self.gridLayout.addWidget(self.TFLineEdit, 0, 1, 1, 3)
        self.MarkerLabel = QtWidgets.QLabel(ModTFTracePopUp)
        self.MarkerLabel.setObjectName("MarkerLabel")
        self.gridLayout.addWidget(self.MarkerLabel, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(ModTFTracePopUp)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(ModTFTracePopUp)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.StartFreqLabel = QtWidgets.QLabel(ModTFTracePopUp)
        self.StartFreqLabel.setObjectName("StartFreqLabel")
        self.gridLayout.addWidget(self.StartFreqLabel, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(ModTFTracePopUp)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 0, 1, 2)
        self.StopFreqLabel = QtWidgets.QLabel(ModTFTracePopUp)
        self.StopFreqLabel.setObjectName("StopFreqLabel")
        self.gridLayout.addWidget(self.StopFreqLabel, 3, 0, 1, 1)
        self.CheckButton = QtWidgets.QPushButton(ModTFTracePopUp)
        self.CheckButton.setObjectName("CheckButton")
        self.gridLayout.addWidget(self.CheckButton, 0, 4, 1, 1)
        self.TFViewer = QtWidgets.QGroupBox(ModTFTracePopUp)
        self.TFViewer.setTitle("")
        self.TFViewer.setFlat(False)
        self.TFViewer.setObjectName("TFViewer")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.TFViewer)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout.addWidget(self.TFViewer, 1, 0, 1, 5)
        self.StartFreqMultCB = QtWidgets.QComboBox(ModTFTracePopUp)
        self.StartFreqMultCB.setObjectName("StartFreqMultCB")
        self.gridLayout.addWidget(self.StartFreqMultCB, 2, 4, 1, 1)
        self.StopFreqMultCB = QtWidgets.QComboBox(ModTFTracePopUp)
        self.StopFreqMultCB.setObjectName("StopFreqMultCB")
        self.gridLayout.addWidget(self.StopFreqMultCB, 3, 4, 1, 1)
        self.StartDSB = QtWidgets.QDoubleSpinBox(ModTFTracePopUp)
        self.StartDSB.setMinimum(0.01)
        self.StartDSB.setMaximum(1e+29)
        self.StartDSB.setObjectName("StartDSB")
        self.gridLayout.addWidget(self.StartDSB, 2, 1, 1, 3)
        self.StopDSB = QtWidgets.QDoubleSpinBox(ModTFTracePopUp)
        self.StopDSB.setMinimum(0.01)
        self.StopDSB.setMaximum(1e+29)
        self.StopDSB.setObjectName("StopDSB")
        self.gridLayout.addWidget(self.StopDSB, 3, 1, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ColorButton = QtWidgets.QPushButton(ModTFTracePopUp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ColorButton.sizePolicy().hasHeightForWidth())
        self.ColorButton.setSizePolicy(sizePolicy)
        self.ColorButton.setMinimumSize(QtCore.QSize(30, 30))
        self.ColorButton.setMaximumSize(QtCore.QSize(30, 30))
        self.ColorButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ColorButton.setText("")
        self.ColorButton.setObjectName("ColorButton")
        self.horizontalLayout.addWidget(self.ColorButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 4)
        self.TraceTypeCB = QtWidgets.QComboBox(ModTFTracePopUp)
        self.TraceTypeCB.setObjectName("TraceTypeCB")
        self.gridLayout.addWidget(self.TraceTypeCB, 5, 1, 1, 4)
        self.MarkersCB = QtWidgets.QComboBox(ModTFTracePopUp)
        self.MarkersCB.setObjectName("MarkersCB")
        self.gridLayout.addWidget(self.MarkersCB, 6, 1, 1, 4)
        self.TraceNameLE = QtWidgets.QLineEdit(ModTFTracePopUp)
        self.TraceNameLE.setObjectName("TraceNameLE")
        self.gridLayout.addWidget(self.TraceNameLE, 7, 1, 1, 4)

        self.retranslateUi(ModTFTracePopUp)
        self.buttonBox.accepted.connect(ModTFTracePopUp.accept) # type: ignore
        self.buttonBox.rejected.connect(ModTFTracePopUp.reject) # type: ignore
        self.ColorButton.clicked.connect(ModTFTracePopUp.ChooseColor) # type: ignore
        self.TFLineEdit.textChanged['QString'].connect(ModTFTracePopUp.textChange) # type: ignore
        self.CheckButton.clicked.connect(ModTFTracePopUp.updateTransferFunction) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ModTFTracePopUp)

    def retranslateUi(self, ModTFTracePopUp):
        _translate = QtCore.QCoreApplication.translate
        ModTFTracePopUp.setWindowTitle(_translate("ModTFTracePopUp", "Modificar curva de transferencia"))
        self.TFLabel.setText(_translate("ModTFTracePopUp", "H(s)"))
        self.label.setText(_translate("ModTFTracePopUp", "Nombre de la curva"))
        self.MarkerLabel.setText(_translate("ModTFTracePopUp", "Marcadores"))
        self.label_3.setText(_translate("ModTFTracePopUp", "Color de curva"))
        self.label_2.setText(_translate("ModTFTracePopUp", "Tipo de Curva"))
        self.StartFreqLabel.setText(_translate("ModTFTracePopUp", "Frec. inicial"))
        self.StopFreqLabel.setText(_translate("ModTFTracePopUp", "Frec. final"))
        self.CheckButton.setText(_translate("ModTFTracePopUp", "Check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModTFTracePopUp = QtWidgets.QDialog()
    ui = Ui_ModTFTracePopUp()
    ui.setupUi(ModTFTracePopUp)
    ModTFTracePopUp.show()
    sys.exit(app.exec())
